<?php
/*
    pfBlockerNG_import_gravity.php
    Copyright (C) 2016 gravity@demarctech.com
    All rights reserved.

    URL and Header data pull from firehole project file update-ipsets.in
    https://github.com/firehol/firehol

    Orginal pfBlockerng_import.php script
    pfBlockerNG
    Copyright (C) 2014 BBcan177@gmail.com
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
        1. Redistributions of source code must retain the above copyright notice,
           this list of conditions and the following disclaimer.
        2. Redistributions in binary form must reproduce the above copyright
           notice, this list of conditions and the following disclaimer in the
           documentation and/or other materials provided with the distribution.
    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.

    Some site require registration:
        https://www.autoshun.org
        https://www.blueliv.com

*/

require_once("config.inc");
require_once("util.inc");
require_once("functions.inc");
require_once("pkg-utils.inc");
require_once("pfsense-utils.inc");
require_once("globals.inc");
require_once("services.inc");

print "";
$pfblist_new=array (
			array ("none"        => "",
			"aliasname"          => "Level_1",
			"description"        => "Provides security against Phishing, Malware and Fraud typical for outbound traffic",
			"infolists"          => "",
			"row"                => array (
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://hosts-file.net/psh.txt",
					"header"     => "hphosts_psh"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://www.badips.com/get/list/any/2",
					"header"     => "badips"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.openbl.org/lists/base_90days.txt",
					"header"     => "openbl_90d"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.stopforumspam.com/downloads/toxic_ip_cidr.txt",
					"header"     => "stopforumspam_toxic"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://botscout.com/last_caught_cache.htm",
					"header"     => "botscout"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://malc0de.com/bl/IP_Blacklist.txt",
					"header"     => "malc0de"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://support.clean-mx.de/clean-mx/xmlphishing?response=alive&format=csv&domain=",
					"header"     => "cleanmx_phishing"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://atlas.arbor.net/summary/phishing.csv",
					"header"     => "atlas_phishing"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://blocklist.greensnow.co/greensnow.txt",
					"header"     => "greensnow"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://freeapi.blueliv.com/v1/crimeserver/last",
					"header"     => "blueliv_crimeserver_last"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://www.maxmind.com/en/anonymous-proxy-fraudulent-ip-address-list",
					"header"     => "maxmind_proxy_fraud"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://hosts-file.net/emd.txt",
					"header"     => "hphosts_emd"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://hosts-file.net/exp.txt",
					"header"     => "hphosts_exp"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://hosts-file.net/hjk.txt",
					"header"     => "hphosts_hjk"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://list.iblocklist.com/?list=llvtlsjyoyiczbkjsxpf&fileformat=p2p&archiveformat=gz",
					"header"     => "iblocklist_spyware"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://feeds.dshield.org/block.txt",
					"header"     => "dshield"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://zeustracker.abuse.ch/blocklist.php?download=badips",
					"header"     => "zeus_badips"),	
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://feodotracker.abuse.ch/blocklist/?download=badips",
					"header"     => "feodo_badips"),		
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt",
					"header"     => "ransomware_rw"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://rules.emergingthreats.net/blockrules/compromised-ips.txt",
					"header"     => "et_compromised"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt",
					"header"     => "et_block"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.spamhaus.org/drop/drop.txt",
					"header"     => "spamhaus_drop"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.spamhaus.org/drop/edrop.txt",
					"header"     => "spamhaus_edrop"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://sslbl.abuse.ch/blacklist/sslipblacklist.csv",
					"header"     => "sslbl"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://labs.snort.org/feeds/ip-filter.blf",
					"header"     => "snort_ipfilter"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://osint.bambenekconsulting.com/feeds/c2-ipmasterlist.txt",
					"header"     => "bambenek_c2"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://reputation.alienvault.com/reputation.generic",
					"header"     => "alienvault_reputation"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://atlas.arbor.net/summary/attacks.csv",
					"header"     => "atlas_attacks"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://atlas.arbor.net/summary/botnets.csv",
					"header"     => "atlas_botnets"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://atlas.arbor.net/summary/fastflux.csv",
					"header"     => "atlas_fastflux"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "https://atlas.arbor.net/summary/scans.csv",
					"header"     => "atlas_scans"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.malwaredomainlist.com/hostslist/ip.txt",
					"header"     => "malwaredomainlist"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.nothink.org/blacklist/blacklist_malware_http.txt",
					"header"     => "nt_malware_http"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.nothink.org/blacklist/blacklist_malware_dns.txt",
					"header"     => "nt_malware_dns"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.nothink.org/blacklist/blacklist_ssh_week.txt",
					"header"     => "nt_ssh_7d"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://danger.rulez.sk/projects/bruteforceblocker/blist.php",
					"header"     => "bruteforceblocker"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://lists.blocklist.de/lists/all.txt",
					"header"     => "blocklist_de"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://cinsscore.com/list/ci-badguys.txt",
					"header"     => "ciarmy")),
            "action"             => "disabled",
            "cron"               => "01hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
			array ("none"        => "",
			"aliasname"          => "Level_2",
			"description"        => "Provides security against well known attackers with the minimum of false positives, use with Level_1",
			"infolists"          => "",
			"row"                => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://feodotracker.abuse.ch/blocklist/?download=ipblocklist",
                    "header"     => "feodo"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist",
                    "header"     => "zeus")),
            "action"             => "disabled",
            "cron"               => "01hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
            "aliasname"          => "Level_3",
            "description"        => "Provides security against well known attackers with the minimum of false positives typically inbound",
            "infolists"          => "",
            "row"                => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base.txt",
                    "header"     => "openbl"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_1days.txt",
                    "header"     => "openbl_1d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_7days.txt",
                    "header"     => "openbl_7d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_30days.txt",
                    "header"     => "openbl_30d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_60days.txt",
                    "header"     => "openbl_60d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_180days.txt",
                    "header"     => "openbl_180d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_360days.txt",
                    "header"     => "openbl_360d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.openbl.org/lists/base_all.txt",
                    "header"     => "openbl_all"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/ssh.txt",
                    "header"     => "blocklist_de_ssh"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/mail.txt",
                    "header"     => "blocklist_de_mail"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/apache.txt",
                    "header"     => "blocklist_de_apache"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/imap.txt",
                    "header"     => "blocklist_de_imap"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/ftp.txt",
                    "header"     => "blocklist_de_ftp"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/sip.txt",
                    "header"     => "blocklist_de_sip"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/strongips.txt",
                    "header"     => "blocklist_de_strongips"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/bruteforcelogin.txt",
                    "header"     => "blocklist_de_bruteforce")),
            "action"             => "disabled",
            "cron"               => "01hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
            "aliasname"          => "Attacks",
            "description"        => "Attacks Expect false positives whitelists will need to be created",
            "infolists"          => "",
            "row"                => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://freeapi.blueliv.com/v1/crimeserver/online",
                    "header"     => "blueliv_crimeserver_online"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://freeapi.blueliv.com/v1/crimeserver/recent",
                    "header"     => "blueliv_crimeserver_recent"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.botvrij.eu/data/ioclist.ip-dst.raw",
                    "header"     => "botvrij_dst"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=czvaehmjpsnwwttrdoyl&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_cruzit_web_attacks"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.darklist.de/raw.php",
                    "header"     => "darklist_de"),
                 array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://charles.the-haleys.org/ssh_dico_attack_hdeny_format.php/hostsdeny.txt",
                    "header"     => "haley_ssh"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=usrcshglbiilevmyfhse&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_hijacked"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://stefan.gofferje.net/sipblocklist.zone",
                    "header"     => "gofferje_sip"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.nothink.org/blacklist/blacklist_malware_irc.txt",
                    "header"     => "nt_malware_irc"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.autoshun.org/download/?api_key=<API KEY>&format=csv",
                    "header"     => "shunlist"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.tc.edu.tw/net/netflow/lkout/recent/30",
                    "header"     => "taichung"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://talosintel.com/feeds/ip-filter.blf",
                    "header"     => "talosintel_ipfilter"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.voipbl.org/update/",
                    "header"     => "voipbl"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.cruzit.com/xwbl2txt.php",
                    "header"     => "cruzit_web_attacks"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.turris.cz/greylist-data/greylist-latest.csv",
                    "header"     => "turris_greylist")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Organisations",
                "description"    => "Organisations",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=imlmncgrkbnacgcwfjvh&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_edu"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=xshktygkujudfnjfioro&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_microsoft"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=mcvxsnihddgutbjfbghy&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_spider"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=aphcqvpxuqgrkgufjruj&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_apple"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=tgbankumtwtrzllndbmb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_logmein"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=cnxkgiklecdaihzukrud&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_steam"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ppqqnyihmcrryraaqsjo&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_xfire"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ercbntshuthyykfkmhxc&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_blizzard"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=etmcrglomupyxtaebzht&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_ubisoft"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=pevkykuhgaegqyayzbnr&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_nintendo"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=gfnxlhxsijzrcuxwzebb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_activision"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=tukpvrvlubsputmkmiwg&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_sony_online"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=eveiyhgmusglurfmjyag&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_crowd_control"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=qnjdimxnaupjmpqolxcv&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_linden_lab"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ejqebpcdmffinaetsvxj&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_electronic_arts"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=odyaqontcydnodrlyina&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_square_enix"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=mwjuwmebrnzyyxpbezxu&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_ncsoft"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=sdlvfabdjvrdttfjotcy&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_riot_games"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=zvwwndvzulqcltsicwdg&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_punkbuster"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=alxugfmeszbhpxqfdits&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_joost"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=aevzidimyvwybzkletsg&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_pandora"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=nzldzlpkgrcncdomnttb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_org_pirate_bay"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=toboaiysofkflwgrttmb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_aol"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=rsgyxvuklicibautguia&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_comcast"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=dwwbsmzirrykdlvpqozb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_cablevision"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=cdmdbprvldivlqsaqjol&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_verizon"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=grbtkzijgrowvobvessf&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_att"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=aqtsnttnqmcucwrjmohd&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_twc"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=htnzojgossawhpkbulqw&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_charter"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=jezlifrpefawuoawnfez&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_qwest"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=twdblifaysaqtypevvdp&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_embarq"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=psaoblrwylfrdsspfuiq&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_suddenlink"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=hngtqrhhuadlceqxbrob&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_isp_sprint"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://blockchain.info/en/connected-nodes",
                    "header"     => "bitcoin_blockchain_info"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://getaddr.bitnodes.io/api/v1/snapshots/latest/",
                    "header"     => "bitcoin_nodes")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Abuse",
                "description"    => "Abuse Expect false positives whitelists will need to be created",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://blocklist.net.ua/blocklist.csv",
                    "header"     => "blocklist_net_ua"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://cleantalk.org/blacklists/submited_today",
                    "header"     => "cleantalk_new"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://cleantalk.org/blacklists/updated_today",
                    "header"     => "cleantalk_updated"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://cleantalk.org/blacklists/top20",
                    "header"     => "cleantalk_top20"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.gpf-comics.com/dnsbl/export.php",
                    "header"     => "gpf_comics"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://graphiclineweb.wordpress.com/tech-notes/ip-blacklist/",
                    "header"     => "graphiclineweb"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/hfs.txt",
                    "header"     => "hphosts_hfs"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.ip-finder.me/ip-full-list/",
                    "header"     => "ipblacklistcloud_top"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.ip-finder.me/download/",
                    "header"     => "ipblacklistcloud_recent"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.myip.ms/files/blacklist/csf/latest_blacklist.txt",
                    "header"     => "myip"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://sblam.com/blacklist.txt",
                    "header"     => "sblam"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ficutxiwawokxlcyoeye&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_forumspam"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/bannedips.zip",
                    "header"     => "stopforumspam"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_1.zip",
                    "header"     => "stopforumspam_1d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_7.zip",
                    "header"     => "stopforumspam_7d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_30.zip",
                    "header"     => "stopforumspam_30d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_90.zip",
                    "header"     => "stopforumspam_90d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_180.zip",
                    "header"     => "stopforumspam_180d"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.stopforumspam.com/downloads/listed_ip_365.zip",
                    "header"     => "stopforumspam_365d")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Malware",
                "description"    => "Malware Expect false positives whitelists will need to be created",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=npkuuhuxcsllnhoamkvm&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_ciarmy_malicious"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://security-research.dyndns.org/pub/malware-feeds/ponmocup-infected-domains-shadowserver.csv",
                    "header"     => "dyndns_ponmocup"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.slcsecurity.com/feedspublic/IP/malicious-ip-dst.txt",
                    "header"     => "jigsaw_malware"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.slcsecurity.com/feedspublic/IP/malicious-ip-src.txt",
                    "header"     => "jigsaw_attacks"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://atrack.h3x.eu/c2",
                    "header"     => "asprox_c2"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://rules.emergingthreats.net/fwrules/emerging-PIX-CC.rules",
                    "header"     => "et_botcc"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://gist.githubusercontent.com/BBcan177/bf29d47ea04391cb3eb0/raw",
                    "header"     => "bbcan177_ms1"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://gist.githubusercontent.com/BBcan177/d7105c242f17f4498f81/raw",
                    "header"     => "bbcan177_ms3"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://public.tableau.com/views/CTAOnlineViz/DashboardData.csv?:embed=y&:showVizHome=no&:showTabs=y&:display_count=y&:display_static_image=y&:bootstrapWhenNotified=true",
                    "header"     => "cta_cryptowall"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://cybercrime-tracker.net/fuckerz.php",
                    "header"     => "cybercrime"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/feeds/csv/",
                    "header"     => "ransomware_feed"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/CW_PS_IPBL.txt",
                    "header"     => "ransomware_cryptowall_ps"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/TC_PS_IPBL.txt",
                    "header"     => "ransomware_teslacrypt_ps"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/LY_C2_IPBL.txt",
                    "header"     => "ransomware_locky_c2"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/LY_PS_IPBL.txt",
                    "header"     => "ransomware_locky_ps"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://sslbl.abuse.ch/blacklist/sslipblacklist_aggressive.csv",
                    "header"     => "sslbl_aggressive"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.threatcrowd.org/feeds/ips.txt",
                    "header"     => "threatcrowd"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.urlvir.com/export-ip-addresses/",
                    "header"     => "urlvir"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.projecthoneypot.org/list_of_ips.php?t=b&rss=1",
                    "header"     => "php_bad"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://vxvault.net/ViriList.php?s=0&m=100",
                    "header"     => "vxvault"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.trustedsec.com/banlist.txt",
                    "header"     => "trustedsec_atif")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Reputation",
                "description"    => "Reputation Expect false positives whitelists will need to be created",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.binarydefense.com/banlist.txt",
                    "header"     => "bds_atif"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/fsa.txt",
                    "header"     => "hphosts_fsa"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/mmt.txt",
                    "header"     => "hphosts_mmt"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/pha.txt",
                    "header"     => "hphosts_pha"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/wrz.txt",
                    "header"     => "hphosts_wrz"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=cwworuawihqvocglcoss&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_badpeers"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=mtxmiireqmjzazcsoiem&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_exclusions"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=jhaoawihmfxgnvmaqffp&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_fornonlancomputers"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ydxerpxkpcfqjaybcssw&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_level1"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=gyisgnzbhppbvsphucsw&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_level2"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=uwnukjqktoggdknzrhgh&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_level3"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=dufcxgnbjsdwmwctgfuj&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_pedophiles"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=plkehquoahljmyxjixpu&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_rangetest"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=ghlzqtqxnzctvvajwwag&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_webexploit"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://nullsecure.org/threatfeed/master.txt",
                    "header"     => "nullsecure"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.packetmail.net/iprep.txt",
                    "header"     => "packetmail"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.packetmail.net/iprep_ramnode.txt",
                    "header"     => "packetmail_ramnode"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.packetmail.net/iprep_CARISIRT.txt",
                    "header"     => "packetmail_carisirt"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.packetmail.net/iprep_mail.txt",
                    "header"     => "packetmail_mail"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.packetmail.net/iprep_emerging_ips.txt",
                    "header"     => "packetmail_emerging_ips")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Spam_Bots_PHP",
                "description"    => "Spam, Bots and PHP Attacks",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://lists.blocklist.de/lists/bots.txt",
                    "header"     => "blocklist_de_bots"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://antispam.imp.ch/spamlist",
                    "header"     => "iw_spamlist"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://blocklist.sigmaprojects.org/api.cfc?method=getList&lists=spammers",
                    "header"     => "sp_spammers"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.projecthoneypot.org/list_of_ips.php?t=s&rss=1",
                    "header"     => "php_spammers"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.dnsbl.manitu.net/download/nixspam-ip.dump.gz",
                    "header"     => "nixspam"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://rules.emergingthreats.net/fwrules/emerging-PIX-DROP.rules",
                    "header"     => "et_spamhaus"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=zbdlwrqkabxbcppvrnos&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_spamhaus_drop"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.chaosreigns.com/iprep/bind_zone.txt",
                    "header"     => "chaosreigns"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://support.clean-mx.de/clean-mx/xmlviruses.php?response=alive&fields=ip",
                    "header"     => "cleanmx_viruses"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/grm.txt",
                    "header"     => "hphosts_grm"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://antispam.imp.ch/wormlist",
                    "header"     => "iw_wormlist"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.unsubscore.com/blacklist.txt",
                    "header"     => "lashback_ubl"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.projecthoneypot.org/list_of_ips.php?t=c&rss=1",
                    "header"     => "php_commenters"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1",
                    "header"     => "php_dictionary"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.projecthoneypot.org/list_of_ips.php?t=h&rss=1",
                    "header"     => "php_harvesters"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://virbl.bit.nl/download/virbl.dnsbl.bit.nl.txt",
                    "header"     => "virbl")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "TOR",
                "description"    => "TOR",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://www.dan.me.uk/torlist/",
                    "header"     => "dm_tor"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://torstatus.blutmagie.de/ip_list_all.php/Tor_ip_list_ALL.csv",
                    "header"     => "bm_tor"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://check.torproject.org/exit-addresses",
                    "header"     => "tor_exits"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/TL_PS_IPBL.txt",
                    "header"     => "ransomware_torrentlocker_ps"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://ransomwaretracker.abuse.ch/downloads/TL_C2_IPBL.txt",
                    "header"     => "ransomware_torrentlocker_c2"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://rules.emergingthreats.net/blockrules/emerging-tor.rules",
                    "header"     => "et_tor"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=togdoptykrlolpddwbvz&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_onion_router")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Anonymizers",
                "description"    => "Anonymizers",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://tools.rosinstrument.com/proxy/l100.xml",
                    "header"     => "ri_web_proxies"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://tools.rosinstrument.com/proxy/plab100.xml",
                    "header"     => "ri_connect_proxies"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.xroxy.com/proxyrss.xml",
                    "header"     => "xroxy"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.sslproxies.org/",
                    "header"     => "sslproxies"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.socks-proxy.net/",
                    "header"     => "socks_proxy"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.proxz.com/proxylists.xml",
                    "header"     => "proxz"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.proxylists.net/proxylists.xml",
                    "header"     => "proxylists"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://txt.proxyspy.net/proxy.txt",
                    "header"     => "proxyspy"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.proxyrss.com/proxylists/all.gz",
                    "header"     => "proxyrss"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=xoebmbyexwuiogmbyprb&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_proxies")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Ads",
                "description"    => "Ads",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://pgl.yoyo.org/adservers/iplist.php?ipformat=plain&showintro=0&mimetype=plaintext",
                    "header"     => "yoyo_adservers"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=dgxtneitpuvgqqcpfulq&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_ads"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://hosts-file.net/ad_servers.txt",
                    "header"     => "hphosts_ats")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
                "aliasname"      => "Unroutable",
                "description"    => "Unroutable",
                "infolists"      => "",
                "row"            => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.team-cymru.org/Services/Bogons/fullbogons-ipv4.txt",
                    "header"     => "fullbogons"),
				array ("format"  => "auto",
					"state"      => "Enabled",
					"url"        => "http://www.team-cymru.org/Services/Bogons/bogon-bn-agg.txt",
					"header"     => "bogons"),
				array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://www.cidr-report.org/bogons/freespace-prefix.txt",
                    "header"     => "cidr_report_bogons"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=bcoepfyewziejvcqyhqo&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_iana_reserved"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=cslpybexmxyuacbyuvib&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_iana_private"),
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "http://list.iblocklist.com/?list=pwqnlynprfgtjbgqoizj&fileformat=p2p&archiveformat=gz",
                    "header"     => "iblocklist_iana_multicast")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled"),
            array ("none"        => "",
            "aliasname"          => "Web_Servers_Only",
            "description"        => "Provides basic security against the most well known attackers with the minimum of false positives",
            "infolists"          => "",
            "row"                => array (
                array ("format"  => "auto",
                    "state"      => "Enabled",
                    "url"        => "https://raw.githubusercontent.com/pushinginertia/ip-blacklist/master/ip_blacklist.conf",
                    "header"     => "pushing_inertia_blocklist")),
            "action"             => "Disabled",
            "cron"               => "04hours",
            "dow"                => "1",
            "aliaslog"           => "enabled",
            "custom"             => "",
            "custom_update"      => "disabled")

            );

print "Checking for Existing pfBlockerNG Alias/Lists\n";

// Check for Existing pfBlockerNG Allias/Lists
if (is_array($config['installedpackages']['pfblockernglistsv4']['config'])) {
   print "Found existing Alias/Lists. Merging Existing Alias/Lists with Imported Version\n\n";
   $pfblist = $config['installedpackages']['pfblockernglistsv4']['config'];
   $pfbfinal = array_merge($pfblist, $pfblist_new);
   $config['installedpackages']['pfblockernglistsv4']['config'] = $pfbfinal;
} else {
   print "No existing Alias/Lists found. Importing new Version.\n\n";
   $config['installedpackages']['pfblockernglistsv4']['config'] = $pfblist_new;
}

print  "pfBlockerNG Alias List Import Completed.";
write_config();

?>;








